language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
    python: 3.7-dev
  password:
    secure: "ZddmRkRNn3SavPRjzIfw3qXUePmrWtaj20vG4fYhb9xB72erfQtD4lNwnwGTr+jtr21CuyaPqod4xdUUQRv3nAnn4005bUGl6DzJ54hSu4A71ZptwDS0PGHM+ROIx2j8Bg8jkcOh8t24eszfxkzS58+ojav+O8ER/ElT5QDpr2R+zhJ01e+VIrePd66W9a/lMlY/eBnEjx44lzvB5lpeil07aB8hOP2Bu7WFFDpoCCTQ0PN3GP40esf9Fh1V6vTeISJyWkC2l2zYV+4ERQLyRBIZPDvXKC3rAInWTh0yHzFJvhTg7k4wUdkzoWE5/PrvcKHPcFxd07QneudJUOdnvAL6np0fRjPM8K6VVO255Twxc/EooO2Sqhg/qXaJCvyWauXrnjbpSwoSHrz6kh3QJtB0/lfJTHGtOessVcIpK5Vexnk1qE7LnCqqF5aZ/nzBVet45KG5KRqlyoHuPlg+/XneKJFmPBSkxZtJzR1Azu/MebXEjLQxEQkxi9Af/fObMX9qqxxsUXcS2iaBRaCQLVrhTXvtnhuJCTRsnRzH/Su79m0JW6aWL3rbWLMhyxxUNL2swes0SIO6/HiCwbpJlHV2UC1bkp8oGbnldZDM5ON+sKaU89QdXRRt3+r5A+tn95VzUGSc16EE1rKw9hz/tqXQDPEvcXEx22tBvwnqSiQ="
