language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=2.7
  - os: linux
    env: PYTHON=3.5
  - os: linux
    env: PYTHON=3.6
  - os: linux
    env: PYTHON=3.7-dev
# language: python
# python:
# - 2.7
# - 3.5
# - 3.6
# - 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
- export CXX=g++-4.8 CC=gcc-4.8
- $CXX --version
- pip install --user --upgrade pip virtualenv
- virtualenv -p python$PYTHON venv
- source venv/bin/activate
install:
- python setup.py sdist
- pip install --verbose dist/*.tar.gz
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
    python: 3.7-dev
  password:
    secure: oQvR8+MublFHsjMZ2kkSzL9kxtMuvF3TRqNfLuvO0rXWpYKvGd8ff3lgXVuc5WvsoPRT0KLEEiL/gMEZ+Ou5k0vL1hUg5mur5S9L1BXgDUQ3erweD2hJTthsuc92GVBCx4ghoWEWPkXyGCS4R+ae3sF5nlonK8wKFoza4O8q0LCU96cjKV66cjPVhySxBnjvjxoTE0ryZ+gSZfON9R96I7kiA0TBGnQNmB5W0uHnkg8yjaKQ8NhZkwIosTc0fRkd021p3fEmhz1U5a9Mrp+UFhjg+Vq6nuFvdE3/jmaNgxfErk8UhodZx4Ey+9CZ85iCJPC7TsFPUi9zuXdyR+kTbGn78RVWn9fhM470YDC2PzFjt/fXptpDqP6+LVfZ6OA6BzfHbuges7XnnNcaQBz63btSvNMADu/8MH2qNjI7F7SLh15j3GgaOOK39FHce5ao+tupZuBWlIAkBQzMtWBtE5OWU7xHzuIswAhK8e2qy/Is3mIR8Dp0Ae6TrUYQjxfqReSAf6GrMnvZwdOBuAOvJMVaBqrSPxwBIetQ20eBc7o0gBIjW/fXB81YVqPR0l51XD5prj2wLRt8eupA4hlDmG4oVSJS/fOBkMUwAFUS9JoChxzlVgSYB/X/qMK1D9w3jskVfCMr8anwA8gG0i+5GZ80hQ7NH7QHTKGEKBeMrVA=
