language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
  password:
    secure: QZNrYc3dWl2r5DZBtCs3/AsHcE/jLOXGqeonMvF0Yy4X633fkaHkxne+ynebSUelP3rBedmBYaHiFB8+eEkuGr0ylXQTA1sSet/L1xIzHLoUHB6Amk7M/9tKK6Sil52Uv45EnFCIwROHiAQivmeVpCIHAQPykF0/L18XP2IX5C9enz42cfagOsYYO+XcePSypvFFheVCKz6T29de63hDQ43oIiyJH8ByW0/KmnytBSv83N63k44Lp2BxvafS3b/OGJEwDvO7PUC/k506Hg2hfu7SEw3vNb30vj+N5ZTEFta9wB5HNVttxLOV5PI33aX94I0ut+cgo1CW8MMb6a3A5c3BU9Yx0MTvFO2G5ha9BAf+wyKwrcNwqkcynPo1IE4cUjub3DudvgFJwMofC3uYl3l6y5fZoBoKVKpPGcvaP+y3n+0xQF3kO+TgpxWlYCw9pyICesVm4FXXsy8A3exBisa/J8o3WhavFot7Evp4KCWzpjB/Lu61sGfCiIzEBBkdk1j04O5iN6/cXiwjUzn/FUbyF7FDMQ4ekZQUatES+gf1QtxiFU4AV+w1iI3mljTRFKEVaNGK0PfhrFNzQECFMghaqISpjHNf411PjL7edLLHk4Mle4/phgIt71sbSacyxtI0nNnBsjv46oWORr3MoMTNPxFUUsTQEiST1Bi9LsI=
