language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
  password:
    secure: "f5y6kQDgQDwsFFAmUjek2jF66jAwSGYm8oShnJD9HnHXsulqwLVhI6981nan1vmxm5YM3+ZGc6mZgK7tU3XXFdAVuqc0ufLSLnnp8c3DNIsAMmj78yO1FLFg+qCIGLQv/lMR3B3IwWL8t7gKJGFwmb61gn3SQ0jx3fonO/S7g8Xp2E9/9VJDA+9l9zuiLAxUid6OLrZgfQ6YI1pkC21ljOmtho41W17ku4fKBgkGXDWlMA8IvZ5Hz9LptxA0XwX6+0x/DcWPlLD++FnbMov5VYTv8sYB7ubuIgsUQzIDYGtcwv4qYyABFptezbr1j2geCRKvkLyrZ50RucCwKb70tgQK48UU5nwE2gzyNcKG7idrzwfLL3J/zI8Jcf5MMCGW2/9Jo7iQv3f4wEJVxWnK4hwlGzroiJmEFkbqdjnVD/epGY+Yf7daZ0MxWTh4BCtokYk8lkT2dOnIcEAqtTbefMujaXtNLzxgMJp+gokbNBbcVtnEvosLqwNFoN84rumBCjEEERk9z2PUc9CYIwuNVhSgP2LVa7jkPk9Vm6mLdiaJo2zfONUGxUJAZmh8iRQxuUslQdDUZl1/hT4H6qR7YHUX1qFPhwhd4WX2vzDLrBetsuZnPnyQOZrMDfO3aI39pTffXd1XDgsKNSvP1OEBx0jFwgqYxGApNl6XWBi26ZQ="
