language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
  password:
    secure: "JQ5l1gAM6QEa/W+In1rrkbQUdSWEUBVOaIqlgUtwd/n35BreebmU908PZ+Jy9ylSmbUglfVqocs32gJgWEoszyv4VL9L8rgLCDb3f6xdtNKNtALqjPwAEj0fwmnabC0EGvZMQb3adko69AZifoAO5FR+EemwvuDvqRyYo7H/q7FfF7keFMBMUrsTYG9RKSRdOvtGddM4+2pgxpdsYbjVjosaUDSD22RQZwgTWPWWV9sLj1n4h0kOxWlmN5bfgCf8IsCLyZjJhBu0bmyEScttVJ3FhDnMMpC+0su7YxjG1OmaBIn2NQervncMUGT6nbLc+hQirFtXbf9tu2UzFyeTIZPTqPB0lth+MGEd3zHYPBFLUgkNEU+K/8ZKCwx4KKyLXeWjqTMr71c2nE2NR1/1i8SzGBoEWQZQtSnX+Qj+Z92/biq+9jJnNupeH/6rlvGc19eKqOnBfixVNFnE+bfgSMk8Agqbwmsrp0icrIOdC3VKtf6aODqQr8BMqfBSR9GEfPRZjAm2mk9InBBCjX5FTvJW+gq5JVktnxCSESbCiatm9hgt9rl2UB/Tuszdzc0Qnna9A51McfYKcTlEoB8NTZm9v00EmjOC2m/XsQEeNsE11LuNEzwD+R4xQ5s6sr07dsNak+JSokxFxwLGVejGv2jfMBg12thaL44/p6aLAkQ="
